# ============================================================
# ESPHome - BLE Scanner zum Finden des Veepeak OBDCheck BLE+
# Hardware: M5Stack ATOM S3 (ESP32-S3)
# ============================================================
#
# Diese Config scannt nur nach BLE-Geräten und gibt
# MAC-Adresse, Name und Service-UUIDs im Log aus.
#
# Anleitung:
#   1. Diese Config flashen
#   2. Veepeak Dongle in OBD-Port stecken (Zündung an)
#   3. ESPHome Logs beobachten
#   4. Nach "IOS-Vlink", "V-LINK", "OBDII" oder "Veepeak" suchen
#   5. MAC-Adresse und Service-UUIDs notieren
#   6. Dann die Haupt-Config (ducato-obd2-atom-s3.yaml) anpassen
# ============================================================

esphome:
  name: ducato-ble-scanner
  friendly_name: "Ducato BLE Scanner"

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino

logger:
  level: VERBOSE

# Kein API/OTA nötig für den Scan, aber WiFi zum Log-Streaming
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: "Ducato-Scanner-Fallback"
    password: "scanner123"

captive_portal:

web_server:
  port: 80

# --- BLE Scanner ---
# Scannt aktiv nach allen BLE-Geräten und loggt sie
esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 100ms
    window: 99ms
  on_ble_advertise:
    - lambda: |-
        // Alle gefundenen Geräte loggen
        ESP_LOGI("ble_scan", "========================================");
        ESP_LOGI("ble_scan", "Gerät gefunden:");
        ESP_LOGI("ble_scan", "  Name: %s", x.get_name().c_str());
        ESP_LOGI("ble_scan", "  MAC:  %s", x.address_str().c_str());
        ESP_LOGI("ble_scan", "  RSSI: %d dBm", x.get_rssi());

        // Service UUIDs ausgeben
        for (auto uuid : x.get_service_uuids()) {
          ESP_LOGI("ble_scan", "  Service UUID: %s", uuid.to_string().c_str());
        }

        // Manufacturer Data ausgeben
        for (auto mfr : x.get_manufacturer_datas()) {
          std::string hex;
          for (auto b : mfr.data) {
            char buf[4];
            snprintf(buf, sizeof(buf), "%02X ", b);
            hex += buf;
          }
          ESP_LOGI("ble_scan", "  Manufacturer: UUID=%s Data=%s",
                   mfr.uuid.to_string().c_str(), hex.c_str());
        }
        ESP_LOGI("ble_scan", "========================================");
