# ============================================================
# Beispiel: Kia Niro EV - Raw PID Text-Sensoren
# ============================================================
#
# Dieses Beispiel zeigt, wie man die erweiterten OBD2-Daten
# eines Kia Niro EV (oder anderer Fahrzeuge mit Mode 22 PIDs)
# als rohe Hex-Strings an Home Assistant uebertraegt.
#
# Konzept:
#   Der ESP32 sendet nur die rohen Hex-Antworten als Text-Sensoren.
#   Die Berechnung der einzelnen Werte (SOC, HV-Spannung, etc.)
#   erfolgt in Home Assistant per Template-Sensor.
#   → Weniger Firmware-Builds, flexible Anpassung in HA.
#
# Quelle der PIDs:
#   https://github.com/meatpiHQ/wican-fw/blob/main/vehicle_profiles/kia/niro-ev.json
#
# Anpassungen:
#   1. MAC-Adresse des OBD2 Dongles eintragen
#   2. BLE UUIDs pruefen (mit BLE-Scanner oder nRF Connect)
#   3. secrets.yaml befuellen
#   4. Board-Typ anpassen (falls nicht M5Stack ATOM S3)
# ============================================================

esphome:
  name: kia-niro-ev-obd2
  friendly_name: "Kia Niro EV OBD2"

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key
  # --- Service-Call: Beliebigen ELM327-Befehl senden ---
  # Aufruf aus HA: service: esphome.kia_niro_ev_obd2_send_elm327_command
  services:
    - service: send_elm327_command
      variables:
        command: string
      then:
        - lambda: |-
            id(elm327_hub).send_custom_command(command + "\r");

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: "Kia-OBD2-Fallback"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# --- Custom Component laden ---
external_components:
  - source:
      type: local
      path: components
    components: [elm327_ble]

# Alternativ direkt von GitHub:
# external_components:
#   - source: github://rubenmuehlhans/esphome-obd2-ble
#     components: [elm327_ble]

# --- BLE ---
esp32_ble_tracker:
  scan_parameters:
    active: true

ble_client:
  - mac_address: "AA:BB:CC:DD:EE:FF"  # ← Deine OBD2-Dongle MAC-Adresse!
    id: elm327_ble_client

# --- ELM327 BLE Hub ---
elm327_ble:
  id: elm327_hub
  ble_client_id: elm327_ble_client
  service_uuid: "0000FFF0-0000-1000-8000-00805F9B34FB"  # ← Deine UUIDs!
  char_tx_uuid: "0000FFF2-0000-1000-8000-00805F9B34FB"
  char_rx_uuid: "0000FFF1-0000-1000-8000-00805F9B34FB"
  request_interval: 2s
  request_timeout: 5s

# ============================================================
# Raw PID Text-Sensoren (Hex-Antwort → Home Assistant)
# ============================================================
# Jede PID wird als roher Hex-String uebertragen.
# Die Berechnung erfolgt in HA per Template-Sensor.
#
# header: ECU-Adresse (ATSH wird automatisch gesendet)
# mode:   OBD2 Mode (0x22 = Enhanced Diagnostic)
# pid:    PID-Nummer (hex)
#
# Kia Niro EV ECU-Adressen:
#   7E4 = BMS (Battery Management System)
#   7C6 = Cluster / Instrumententafel

text_sensor:
  # --- PID 2201019: HV-Batterie Hauptdaten (ECU 7E4) ---
  # Enthaelt: SOC, Regen-Max, Power-Max, HV-Strom/Spannung,
  #           Temperaturen, Zellspannungen, 12V, kWh geladen
  - platform: elm327_ble
    type: raw_pid
    name: "Kia BMS 01019 Raw"
    mode: 0x22
    pid: 0x01019
    header: "7E4"

  # --- PID 2201057: HV-Batterie Zusatzdaten (ECU 7E4) ---
  # Enthaelt: SOH, SOC Display, Zell-Degradation Min/Max
  - platform: elm327_ble
    type: raw_pid
    name: "Kia BMS 01057 Raw"
    mode: 0x22
    pid: 0x01057
    header: "7E4"

  # --- PID 22B002: Kilometerstand (ECU 7C6) ---
  # Enthaelt: Odometer
  - platform: elm327_ble
    type: raw_pid
    name: "Kia Cluster B002 Raw"
    mode: 0x22
    pid: 0xB002
    header: "7C6"

  # --- Debug: Letzte Rohantwort (alle Antworten) ---
  - platform: elm327_ble
    type: raw
    name: "Letzte ELM327 Antwort"

  # --- Fehlercodes ---
  - platform: elm327_ble
    type: dtc
    name: "Aktive Fehlercodes"

  - platform: wifi_info
    ip_address:
      name: "IP-Adresse"
    ssid:
      name: "WLAN"

# --- Status-Sensoren ---
binary_sensor:
  - platform: elm327_ble
    type: connected
    name: "ELM327 verbunden"

# --- System-Sensoren ---
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Laufzeit"

# ============================================================
# Home Assistant Template-Sensoren (Beispiel)
# ============================================================
# Die folgenden Template-Sensoren gehoeren in die HA
# configuration.yaml (NICHT in diese ESPHome-Config!).
# Sie zerlegen die Hex-Antwort und berechnen die Werte.
#
# Hinweis: Die Byte-Indizes in den Formeln beziehen sich auf
# die Response NACH dem Mode+PID Prefix.
# Beispiel: Response "6201019..." → Daten beginnen ab Byte 7
# (3 Bytes fuer "62", dann 5 Zeichen fuer "01019")
#
# In der Response "6201019XXYY..." ist:
#   B1  = Position 7-8   (Zeichen 14-15 im Hex-String)
#   B10 = Position 25-26 (Zeichen 18+2*9=36 bis 37)
#   usw.
#
# Beispiel fuer configuration.yaml in Home Assistant:
#
# template:
#   - sensor:
#       # SOC (State of Charge): Byte 10 / 2
#       - name: "Kia HV Batterie SOC"
#         state: >
#           {% set raw = states('sensor.kia_bms_01019_raw') %}
#           {% if raw and raw | length > 26 %}
#             {{ (raw[24:26] | int(base=16)) / 2 }}
#           {% else %}
#             unknown
#           {% endif %}
#         unit_of_measurement: "%"
#         device_class: battery
#
#       # HV Spannung: [Byte19:Byte20] / 10
#       - name: "Kia HV Spannung"
#         state: >
#           {% set raw = states('sensor.kia_bms_01019_raw') %}
#           {% if raw and raw | length > 46 %}
#             {{ ((raw[42:44] | int(base=16)) * 256 +
#                 (raw[44:46] | int(base=16))) / 10 }}
#           {% else %}
#             unknown
#           {% endif %}
#         unit_of_measurement: "V"
#         device_class: voltage
#
#       # 12V Bordnetz: Byte 38 * 0.1
#       - name: "Kia 12V Bordnetz"
#         state: >
#           {% set raw = states('sensor.kia_bms_01019_raw') %}
#           {% if raw and raw | length > 82 %}
#             {{ (raw[80:82] | int(base=16)) * 0.1 }}
#           {% else %}
#             unknown
#           {% endif %}
#         unit_of_measurement: "V"
#         device_class: voltage
#
#       # SOH (State of Health): [Byte34:Byte35] / 10
#       - name: "Kia HV Batterie SOH"
#         state: >
#           {% set raw = states('sensor.kia_bms_01057_raw') %}
#           {% if raw and raw | length > 76 %}
#             {{ ((raw[72:74] | int(base=16)) * 256 +
#                 (raw[74:76] | int(base=16))) / 10 }}
#           {% else %}
#             unknown
#           {% endif %}
#         unit_of_measurement: "%"
#
#       # Kilometerstand: [Byte5:Byte6]
#       - name: "Kia Kilometerstand"
#         state: >
#           {% set raw = states('sensor.kia_cluster_b002_raw') %}
#           {% if raw and raw | length > 18 %}
#             {{ (raw[14:16] | int(base=16)) * 256 +
#                (raw[16:18] | int(base=16)) }}
#           {% else %}
#             unknown
#           {% endif %}
#         unit_of_measurement: "km"
#         device_class: distance
