# ============================================================
# Beispiel: ESPHome OBD2 mit elm327_ble Custom Component
# ============================================================
#
# Diese Config nutzt die elm327_ble Custom Component.
# Vergleiche mit ducato-obd2-atom-s3.yaml (Standalone-Version
# mit Inline-Lambdas) -- die Component-Version ist deutlich
# kürzer und einfacher zu konfigurieren.
#
# Anpassungen:
#   1. MAC-Adresse des Veepeak eintragen
#   2. BLE UUIDs prüfen (mit BLE-Scanner oder nRF Connect)
#   3. secrets.yaml befüllen
#   4. Nicht benötigte Sensoren entfernen/auskommentieren
# ============================================================

esphome:
  name: ducato-obd2
  friendly_name: "Ducato OBD2"

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: "Ducato-OBD2-Fallback"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# --- Custom Component laden ---
external_components:
  - source:
      type: local
      path: components
    components: [elm327_ble]

# Alternativ direkt von GitHub:
# external_components:
#   - source: github://DEIN_USER/esphome-obd2-ble
#     components: [elm327_ble]

# --- BLE ---
esp32_ble_tracker:
  scan_parameters:
    active: true

ble_client:
  - mac_address: "AA:BB:CC:DD:EE:FF"  # ← Deine Veepeak MAC-Adresse!
    id: elm327_ble_client

# --- ELM327 BLE Hub ---
elm327_ble:
  id: elm327_hub
  ble_client_id: elm327_ble_client
  service_uuid: "0000FFF0-0000-1000-8000-00805F9B34FB"
  char_tx_uuid: "0000FFF2-0000-1000-8000-00805F9B34FB"
  char_rx_uuid: "0000FFF1-0000-1000-8000-00805F9B34FB"
  request_interval: 2s
  request_timeout: 5s

# --- OBD2 Sensoren ---
# Einfach den "type" angeben - Name, Einheit, Icon und
# PID-Formel werden automatisch gesetzt.
sensor:
  - platform: elm327_ble
    type: coolant_temp
    name: "Motortemperatur"

  - platform: elm327_ble
    type: rpm
    name: "Drehzahl"

  - platform: elm327_ble
    type: speed
    name: "Geschwindigkeit"

  - platform: elm327_ble
    type: engine_load
    name: "Motorlast"

  - platform: elm327_ble
    type: intake_temp
    name: "Ansauglufttemperatur"

  - platform: elm327_ble
    type: fuel_level
    name: "Kraftstoffstand"

  - platform: elm327_ble
    type: throttle
    name: "Drosselklappe"

  - platform: elm327_ble
    type: battery_voltage
    name: "Batteriespannung"

  - platform: elm327_ble
    type: intake_map
    name: "Ansaugkrümmerdruck"

  - platform: elm327_ble
    type: maf
    name: "Luftmassenmesser"

  - platform: elm327_ble
    type: engine_runtime
    name: "Motorlaufzeit"

  - platform: elm327_ble
    type: oil_temp
    name: "Motoröltemperatur"

  - platform: elm327_ble
    type: ambient_temp
    name: "Umgebungstemperatur"

  - platform: elm327_ble
    type: ecu_voltage
    name: "ECU Spannung"

  - platform: elm327_ble
    type: fuel_rate
    name: "Kraftstoffverbrauch"

  - platform: elm327_ble
    type: baro_pressure
    name: "Barometrischer Druck"

  - platform: elm327_ble
    type: egr
    name: "Abgasrückführung"

  # Eigenen PID abfragen (ohne vordefinierten Typ):
  # - platform: elm327_ble
  #   name: "Mein Custom PID"
  #   mode: 0x01
  #   pid: 0x21
  #   unit_of_measurement: "Schritte"
  #   accuracy_decimals: 0

  # ESP32 Systemsensoren
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Laufzeit"

# --- Fehlerspeicher & Debug ---
text_sensor:
  - platform: elm327_ble
    type: dtc
    name: "Aktive Fehlercodes"

  - platform: elm327_ble
    type: raw
    name: "Letzte ELM327 Antwort"

  - platform: wifi_info
    ip_address:
      name: "IP-Adresse"
    ssid:
      name: "WLAN"

# --- BLE-Verbindung steuern ---
switch:
  - platform: elm327_ble
    name: "ELM327 Verbindung"

# --- Status-Sensoren ---
binary_sensor:
  - platform: elm327_ble
    type: connected
    name: "ELM327 verbunden"

  - platform: elm327_ble
    type: engine_running
    name: "Motor läuft"
